added build to .gitignore
giliyoffe/git-example pull request #1
Opened 2018-06-30 14:47 UTC by orYoffe

fucking merge that shit!!!!!!!!!!!!!!!!!!!!!!!!! 😜

2018-06-30 14:50 UTC, giliyoffe approved these changes

2018-06-30 14:51 UTC, giliyoffe commented on .gitignore
> + Logs
change to oijniosdi ubosidnf punoadsfgfnpiu bnapdfingf oadsnpoadsndfpij basdfgoikandsofnp sajnfp';

2018-06-30 14:52 UTC, giliyoffe requested changes
change it to "sdsdsds sdd sd"

2023-03-13 15:45 UTC, orYoffe commented
coworker found this at work today

2023-12-18 08:36 UTC, closed without merging